version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nl_to_sql_postgres
    environment:
      POSTGRES_DB: nl_to_sql_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/sample_data:/docker-entrypoint-initdb.d
      - ./data/processed:/data/processed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: